import {Block} from '../util/types';

const blocks: Array<Block> = [
  {
    week: null, number: null,
    name: 'Brown Shelf', size: {width: 2.5, height: 2.5},
    tags: ['border', 'shelf'],
    type: 'border',
    file: 'wood',
    difficulty: 1,
  },
  {
    week: null, number: null,
    name: 'Gray Shelf', size: {width: 2.5, height: 2.5},
    tags: ['border', 'shelf'],
    type: 'border',
    file: 'stone',
    difficulty: 1,
  },
  {
    week: 1, number: 1,
    name: 'Crystal Ball', size: {width: 10, height: 10},
    tags: ['books', 'crystal', 'ball'],
    type: 'original',
    difficulty: 2,
  },
  {
    week: 1, number: 2,
    name: 'Crystal Ball with optional extra book', size: {width: 10, height: 10},
    tags: ['books', 'crystal', 'ball'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 1, number: 3,
    name: 'Crystal Ball with alternative base', size: {width: 10, height: 10},
    tags: ['books', 'crystal', 'ball'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 2, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 2, number: 2,
    name: 'Books with optional extra books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'variation',
    difficulty: 1,
  },
  {
    week: 3, number: 1,
    name: 'Books with potion bottle', size: {width: 10, height: 10},
    tags: ['books', 'potion', 'bottle'],
    type: 'original',
    difficulty: 2,
  },
  {
    week: 3, number: 2,
    name: 'Books with potion bottle', size: {width: 10, height: 10},
    tags: ['books', 'potion', 'bottle'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 3, number: 3,
    name: 'Books with Deathly Hallows', size: {width: 10, height: 10},
    tags: ['books', 'deathly', 'hallows'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 3, number: 4,
    name: 'Books with Dark Mark', size: {width: 10, height: 10},
    tags: ['books', 'dark', 'mark'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 4, number: 1,
    name: 'Harry\'s Glasses', size: {width: 10, height: 10},
    tags: ['books', 'glasses'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 4, number: 2,
    name: 'Harry\'s Glasses', size: {width: 10, height: 10},
    tags: ['books', 'glasses'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 4, number: 3,
    name: 'Harry\'s Glasses', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 4, number: 4,
    name: 'Hand of Glory', size: {width: 10, height: 10},
    tags: ['hand', 'glory'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 5, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 6, number: 1,
    name: 'Stoppered Vial', size: {width: 10, height: 10},
    tags: ['books', 'stoppered', 'vial'],
    type: 'original',
    difficulty: 2,
  },
  {
    week: 6, number: 2,
    name: 'Stoppered Vial', size: {width: 10, height: 10},
    tags: ['books', 'stoppered', 'vial'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 6, number: 3,
    name: 'Picture frame', size: {width: 10, height: 10},
    tags: ['picture', 'frame'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 6, number: 4,
    name: 'Slytherin\'s Locket', size: {width: 10, height: 10},
    tags: ['hand', 'slytherin', 'locket'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 7, number: 1,
    name: 'Time Turner', size: {width: 10, height: 10},
    tags: ['books', 'time', 'turner'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 7, number: 2,
    name: 'Time Turner', size: {width: 10, height: 10},
    tags: ['books', 'time', 'turner'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 7, number: 3,
    name: 'Venomous Tentacula', size: {width: 10, height: 10},
    tags: ['picture', 'venomous', 'tentacula'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 8, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books',],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 9, number: 1,
    name: 'Golden Snitch', size: {width: 10, height: 10},
    tags: ['books',],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 9, number: 2,
    name: 'House tie Hufflepuff', size: {width: 10, height: 10},
    tags: ['books', 'tie', 'hufflepuff'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 9, number: 3,
    name: 'House tie Ravenclaw', size: {width: 10, height: 10},
    tags: ['books', 'tie', 'ravenclaw'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 9, number: 4,
    name: 'House tie Griffindor', size: {width: 10, height: 10},
    tags: ['books', 'tie', 'griffindor'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 9, number: 5,
    name: 'House tie Slytherin', size: {width: 10, height: 10},
    tags: ['books', 'tie', 'slytherin'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 10, number: 1,
    name: 'Standard Book of Spells (6)', size: {width: 10, height: 10},
    tags: ['books', 'standard', 'spells'],
    type: 'original',
    difficulty: 2,
  },
  {
    week: 10, number: 2,
    name: 'Standard Book of Spells (7)', size: {width: 10, height: 10},
    tags: ['books', 'standard', 'spells'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 11, number: 1,
    name: 'Hedwig', size: {width: 10, height: 10},
    tags: ['book', 'owl', 'hedwig'],
    type: 'original',
    difficulty: 4,
  },
  {
    week: 11, number: 2,
    name: 'Eagle owl', size: {width: 10, height: 10},
    tags: ['book', 'eagle', 'owl'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 11, number: 3,
    name: 'Errol', size: {width: 10, height: 10},
    tags: ['book', 'errol', 'owl'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 11, number: 4,
    name: 'Pigwidgeon', size: {width: 10, height: 10},
    tags: ['books', 'owl', 'pigwidgeon', 'owl'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 12, number: 1,
    name: 'Basilisk Fang', size: {width: 10, height: 10},
    tags: ['books', 'basilisk', 'fang'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 12, number: 2,
    name: 'Butterbeer', size: {width: 10, height: 10},
    tags: ['book', 'butterbeer'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 12, number: 3,
    name: 'Cooking Sherry', size: {width: 10, height: 10},
    tags: ['book', 'cooking', 'sherry'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 13, number: 1,
    name: 'Monster Book of Monsters', size: {width: 10, height: 10},
    tags: ['monster', 'book', 'fang'],
    type: 'original',
    difficulty: 4,
  },
  {
    week: 13, number: 2,
    name: 'Quirrell\'s Turban', size: {width: 10, height: 10},
    tags: ['books', 'quirrell', 'turban'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 14, number: 1,
    name: 'Magic Wand', size: {width: 10, height: 10},
    tags: ['books', 'magic', 'wand'],
    type: 'original',
    difficulty: 2,
  },
  {
    week: 14, number: 2,
    name: 'Harry\'s Wand', size: {width: 10, height: 10},
    tags: ['books', 'harry', 'wand'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 14, number: 3,
    name: 'Elder Wand', size: {width: 10, height: 10},
    tags: ['books', 'elder', 'wand'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 14, number: 4,
    name: 'Voldemort\'s Wand', size: {width: 10, height: 10},
    tags: ['books', 'voldemort', 'wand'],
    type: 'variation',
    difficulty: 2,
  },
  {
    week: 15, number: 1,
    name: 'Tom Riddle\'s Destroyed Diary', size: {width: 10, height: 10},
    tags: ['books', 'tom', 'riddle', 'diary'],
    type: 'original',
    difficulty: 4,
  },
  {
    week: 15, number: 2,
    name: 'Tom Riddle\'s Intact Diary', size: {width: 10, height: 10},
    tags: ['books', 'tom', 'riddle', 'diary'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 15, number: 3,
    name: 'Books & Potion', size: {width: 10, height: 10},
    tags: ['books', 'potion'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 15, number: 4,
    name: 'Lockhart\'s Peacock Feather Quill & Ink', size: {width: 10, height: 10},
    tags: ['books', 'lockhart', 'peacock', 'feather', 'quill', 'ink'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 16, number: 1,
    name: 'Book with Broomstick', size: {width: 10, height: 10},
    tags: ['books', 'broomstick'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 16, number: 2,
    name: 'Books & Pigmy Puff ', size: {width: 10, height: 10},
    tags: ['books', 'pigmy', 'puff'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 16, number: 3,
    name: 'Simple Book (no broomstick)', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 17, number: 1,
    name: 'Weasley\'s Wizard Wheezes Bag', size: {width: 10, height: 10},
    tags: ['books', 'weasley', 'wizard', 'wheezes', 'bag'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 17, number: 2,
    name: 'Death Eater Mask', size: {width: 10, height: 10},
    tags: ['death', 'eater', 'mask'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 18, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 18, number: 2,
    name: 'Books with extra books', size: {width: 10, height: 10},
    tags: ['books', 'extra'],
    type: 'variation',
    difficulty: 1,
  },
  {
    week: 18, number: 3,
    name: 'Potion book', size: {width: 10, height: 10},
    tags: ['potion', 'book'],
    type: 'variation',
    difficulty: 1,
  },
  {
    week: 18, number: 4,
    name: 'Potion book with extra books', size: {width: 10, height: 10},
    tags: ['potion', 'books', 'extra'],
    type: 'variation',
    difficulty: 1,
  },

  {
    week: 19, number: 1,
    name: 'Hogwarts crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'hogwarts'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 19, number: 2,
    name: 'Hogwarts crest (simple)', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'hogwarts'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 3,
    name: 'Slytherin crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'slytherin'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 4,
    name: 'Slytherin crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'slytherin'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 5,
    name: 'Slytherin crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'slytherin'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 6,
    name: 'Ravenclaw crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'ravenclaw'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 7,
    name: 'Ravenclaw crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'ravenclaw'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 8,
    name: 'Ravenclaw crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'ravenclaw'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 9,
    name: 'Hufflepuff crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'hufflepuff'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 10,
    name: 'Hufflepuff crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'hufflepuff'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 11,
    name: 'Hufflepuff crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'hufflepuff'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 12,
    name: 'Gryffindor crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'griffindor'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 13,
    name: 'Gryffindor crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'griffindor'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 14,
    name: 'Gryffindor crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'griffindor'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 15,
    name: 'Beauxbatons crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'beauxbatons'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 16,
    name: 'Beauxbatons crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'beauxbatons'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 17,
    name: 'Beauxbatons crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'beauxbatons'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 18,
    name: 'Durmstrang crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'durmstrang'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 19,
    name: 'Durmstrang crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'durmstrang'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 19, number: 20,
    name: 'Durmstrang crest', size: {width: 10, height: 10},
    tags: ['books', 'crest', 'durmstrang'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 20, number: 1,
    name: 'Candle', size: {width: 10, height: 10},
    tags: ['books', 'candle'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 20, number: 2,
    name: 'Bluebell Flame in a Jam Jar', size: {width: 10, height: 10},
    tags: ['books', 'bluebell', 'flame', 'jam', 'jar'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 21, number: 1,
    name: 'Sorting Hat', size: {width: 20, height: 10},
    tags: ['books', 'sorting', 'hat'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 21, number: 2,
    name: 'Sorting Hat with Crookshanks', size: {width: 20, height: 10},
    tags: ['books', 'sorting', 'hat', 'cat', 'crookshanks'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 21, number: 3,
    name: 'Nagini', size: {width: 20, height: 10},
    tags: ['books', 'nagini'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 23, number: 1,
    name: 'Quill', size: {width: 10, height: 10},
    tags: ['books', 'quill'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 23, number: 2,
    name: 'Umbridge\'s Quill', size: {width: 10, height: 10},
    tags: ['books', 'umbridge', 'quill'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 23, number: 3,
    name: 'Quick Quotes Quill', size: {width: 10, height: 10},
    tags: ['books', 'quick', 'quotes', 'quill'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 24, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 25, number: 1,
    name: 'Open book', size: {width: 10, height: 10},
    tags: ['books', 'open'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 25, number: 2,
    name: 'Quaffle', size: {width: 10, height: 10},
    tags: ['book', 'quaffle'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 25, number: 3,
    name: 'Dragon eggs', size: {width: 10, height: 10},
    tags: ['dragon', 'egg'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 26, number: 1,
    name: 'Books', size: {width: 10, height: 10},
    tags: ['books'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 26, number: 2,
    name: 'Acromantula', size: {width: 10, height: 10},
    tags: ['book', 'acromantula'],
    type: 'variation',
    difficulty: 1,
  },
  {
    week: 27, number: 1,
    name: 'Teacup', size: {width: 10, height: 10},
    tags: ['books', 'teacup'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 27, number: 2,
    name: 'Teacup', size: {width: 10, height: 10},
    tags: ['books', 'teacup'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 27, number: 3,
    name: 'Half-Moon Spectacles', size: {width: 10, height: 10},
    tags: ['books', 'half', 'moon', 'spectacles', 'glasses'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 27, number: 4,
    name: 'Chocolate Frog Box', size: {width: 10, height: 10},
    tags: ['books', 'chocolate', 'frog', 'box'],
    type: 'variation',
    difficulty: 3,
  },
  {
    week: 28, number: 1,
    name: 'Trevor', size: {width: 10, height: 10},
    tags: ['books', 'trevor', 'toad'],
    type: 'original',
    difficulty: 4,
  },
  {
    week: 28, number: 2,
    name: 'Trevor', size: {width: 10, height: 10},
    tags: ['books', 'trevor', 'toad'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 28, number: 3,
    name: 'Unrolled Parchment Scroll', size: {width: 10, height: 10},
    tags: ['books', 'parchment', 'scroll'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 28, number: 4,
    name: 'Unicorn Head Book End', size: {width: 10, height: 10},
    tags: ['books', 'unicorn', 'head'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 28, number: 5,
    name: 'Baby Norbert', size: {width: 10, height: 10},
    tags: ['books', 'norbert', 'dragon'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 28, number: 6,
    name: 'Bats', size: {width: 10, height: 10},
    tags: ['books', 'bats'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 28, number: 7,
    name: 'Aberforth\'s Eye in Sirius\' Mirror', size: {width: 10, height: 10},
    tags: ['books', 'aberforth', 'eye', 'mirror'],
    type: 'variation',
    difficulty: 4,
  },
  {
    week: 29, number: 1,
    name: 'Cauldron', size: {width: 10, height: 10},
    tags: ['cauldron'],
    type: 'original',
    difficulty: 1,
  },
  {
    week: 29, number: 2,
    name: 'Pumpkin', size: {width: 10, height: 10},
    tags: ['pumpkin'],
    type: 'variation',
    difficulty: 1,
  },
  {
    week: 30, number: 1,
    name: 'Bertie Bott\'s Every Flavour Beans', size: {width: 10, height: 10},
    tags: ['books', 'bertie', 'bott', 'every', 'flavor', 'beans'],
    type: 'original',
    difficulty: 3,
  },
  {
    week: 30, number: 2,
    name: 'Potion Bottles', size: {width: 10, height: 10},
    tags: ['books', 'potion', 'bottles'],
    type: 'variation',
    difficulty: 3,
  },
];

export {blocks as default};
